/* Generated By:JJTree: Do not edit this line. BSHByTree.java */
package bsh;




/**
 * DOCUMENT ME!
 *
 * @author $author$
 * @version $Revision$
  */
public class BSHByTree extends SimpleNode {
	
    /**
     * Creates a new BSHByTree object.
     *
     * @param id DOCUMENT ME!
     */
    public BSHByTree(int id) {
        super(id);
    }
}
